
package cn.itcast.crm.service.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://ws.service.crm.itcast.cn/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activeEmail", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.ActiveEmail")
    @ResponseWrapper(localName = "activeEmailResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.ActiveEmailResponse")
    public void activeEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByAddress", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByAddress")
    @ResponseWrapper(localName = "findByAddressResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByAddressResponse")
    public String findByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itcast.crm.service.ws.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.ws.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByEmail", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByEmail")
    @ResponseWrapper(localName = "findByEmailResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByEmailResponse")
    public Customer findByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.ws.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itcast.crm.service.ws.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateFixedAreaIdById", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.UpdateFixedAreaIdById")
    @ResponseWrapper(localName = "updateFixedAreaIdByIdResponse", targetNamespace = "http://ws.service.crm.itcast.cn/", className = "cn.itcast.crm.service.ws.UpdateFixedAreaIdByIdResponse")
    public void updateFixedAreaIdById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
